$("#head").css("text-align","center").css("color","white")
$("table").css("margin-left","auto").css("margin-right","auto").css("width","50%").css("border","1px solid white")
$(".tablehead").css("color","white")
$(".blue").css("background-color","blue")
$(".green").css("background-color","green")
$(".red").css("background-color","red")
$(".yellow").css("background-color","yellow")
$(".day").css("margin-left","30vw").css("color","white")
$("body").css("background-color","black")